apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-project
  name: sample-project
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sample-project
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-project
    spec:
      containers:
      - image: sarthaksatish/sample-project:3.0
        imagePullPolicy: IfNotPresent
        name: sample-project
        ports:
        - containerPort: 8080
          protocol: TCP
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2026-10-06T17:04:54Z"
    lastUpdateTime: "2026-10-06T17:04:57Z"
    message: ReplicaSet "sample-project-58d767dd56" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-10-06T17:07:11Z"
    lastUpdateTime: "2026-10-06T17:07:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
